name: 'glamira'
version: '1.0.0'
config-version: 2

profile: 'glamira'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  glamira:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table  
      +schema: marts
