
version: 2

models:
    - name: stg_dim_location
      description: "Staging location dimensions"
      columns:
          - name: location_key
            description: "Hashing country&region&city to implement location primary key"
          - name: country
            description: "Country name"
          - name: region
            description: "Region name"
          - name: city
            description: "City name"
          - name: ip
            description: "Keep ip field to replace ip in fact tables"
          
    - name: stg_dim_user
      description: "User informations"
      columns:
          - name: user_pk
            description: "User ID - Primary key"
          - name: user_email
            description: "User email address"

    - name: stg_dim_device
      description: "User device information"
      columns:
          - name: device_id
            description: "Device ID - Primary key"
          - name: resolution
            description: "Device resolution"
          - name: operating_system
            description: "Operating System name"
          - name: device_name
            description: "Device name"
        
    - name: stg_exchange_rate
      description: "Local currency to USD exchange rate"
      columns:
          - name: currency_pk
            description: "Currency exchange - Primary key"
          - name: currency_symbol
            description: "Currency symbol"
          - name: currency_code
            description: "Currency code, 3 characters"
          - name: currency_name
            description: "Currency name"
          - name: exchange_rate
            description: "Exchange rate in float64"

    - name: stg_dim_product
      description: "Product dimensions"
      columns:
        - name: product_id,
          description: ""
        - name: product_name,
          description: ""
        - name: sku,
          description: ""
        - name: gender,
          description: ""
        - name: category_name,
          description: ""
        - name: collection_name,
          description: ""
        - name: category_name,
          description: ""
        - name: product_type,
          description: ""
        - name: gold_weight,
          description: ""
        - name: platinum_palladium_info_in_alloy
          description: ""