# models/marts/schema.yml
version: 2

models:
  - name: dim_calendar
    description: "Calendar dimension table with date attributes for time-based analysis"
    columns:
      - name: date_key
        description: "Primary key - date in YYYYMMDD format"
        tests:
          - not_null
          - unique

      - name: date_day
        description: "The actual date value"
        tests:
          - not_null

      - name: year
        description: "4-digit year"
        tests:
          - not_null

      - name: month
        description: "Month number (1-12)"
        tests:
          - not_null

      - name: quarter
        description: "Quarter number (1-4)"
        tests:
          - not_null

      - name: day_of_week
        description: "Day of week (1=Sunday, 7=Saturday)"
        tests:
          - not_null

      - name: is_weekend
        description: "Boolean flag for weekend"
        tests:
          - not_null

      - name: is_weekday
        description: "Boolean flag for weekday"
        tests:
          - not_null

  - name: dim_location
    description: "User location based on IP address"
    columns:
      - name: location_pk
        description: "Primary key"
        tests:
          - not_null
          - unique
      
      - name: country_code
        description: "Country code with 3 letters, capitalized"
        tests:
          - not_null

      - name: region_name
        description: "Full region names"
        tests:
          - not_null

      - name: city_name
        description: "Full city names"
        tests:
          - not_null

  - name: dim_device
    description: "User device informations"
    columns:
      - name: device_pk
        description: "Primary key"
        tests:
          - not_null
          - unique
      
      - name: resolution
        description: "User device resolution"
        tests:
          - not_null

      - name: operating_system
        description: "Device's running operating system"
        tests:
          - not_null

      - name: device_name
        description: "Device name"
        tests:
          - not_null
